/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.gft.sample.openapi.integrationtesting.v1.api

import com.gft.sample.openapi.integrationtesting.v1.model.Account
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import javax.validation.Valid

@Validated
@RequestMapping("\${api.base-path:/v1}")
interface AccountControllerApi {


    @RequestMapping(
            value = ["/accounts"],
            produces = ["application/json"], 
            consumes = ["application/json"],
            method = [RequestMethod.POST])
    fun createAccount( @Valid @RequestBody account: Account
): ResponseEntity<Account> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @RequestMapping(
            value = ["/accounts"],
            produces = ["application/json"], 
            method = [RequestMethod.GET])
    fun getAccounts(): ResponseEntity<List<Account>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @RequestMapping(
        value = ["/accounts/{accountId}"],
        produces = ["application/json"],
        method = [RequestMethod.DELETE])
    fun deleteAccount( @PathVariable("accountId") accountId: java.util.UUID
    ): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
